### ISSUE TITLE
Should this project contain/support a GitHub Action for shellcheck?

### ISSUE THREAD

**Issue by cclauss** [koalaman/shellcheck#1492]
Should this project contain the code for a simple yet flexible GitHub Action that allows repo maintainers to quickly add automated shellcheck testing on all pull requests submitted to their repos?

Putting that code into this repo or another koalaman repo will focus development efforts on a single, community-supported GitHub Action for shellcheck instead of a multitude of homegrown solutions.

Currently you must be in the GitHub Action beta to be able to use Actions.

https://github.com/marketplace/actions/haskell-linter

**Comment by cclauss** [comment]
https://github.com/actions/bin/tree/master/shellcheck

**Comment by koalaman** [comment]
I'm now on the beta waitlist. I don't if or when I'll get approved, but I'll have a look then.

**Comment by thomasleplus** [comment]
Any update? I'd would really like to use an "official" shellcheck action. Thanks

**Comment by cclauss** [comment]
What is wrong with https://github.com/marketplace/actions/shellcheck ?

**Comment by szepeviktor** [comment]
Even GHA images include shellcheck - through APT packages: https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md

**Comment by evulhotdog** [comment]
Reviewdog supports it, if you want shellcheck w/ Github Annotations.

```
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          path: "." # Optional.
          pattern: "*.sh" # Optional.
          filter_mode: nofilter # Optional.
          fail_on_error: true
```
