### ISSUE TITLE
Add wiki page for Drone

### ISSUE THREAD

**Issue by loganmarchione** [koalaman/shellcheck#2067]
#### For bugs
N/A

#### For new checks and feature suggestions
N/A

#### Here's a snippet or screenshot that shows the problem:
Add wiki page for [Drone](https://drone.io/) CI/CD system. I would do it myself, but I don't believe you can submit a PR to a wiki

```yaml
---
kind: pipeline
type: docker
name: default

steps:
  - name: shellcheck
    image: koalaman/shellcheck-alpine:stable
    commands:
      - "shellcheck testScript.sh"
```

#### Here's what shellcheck currently says:
N/A

#### Here's what I wanted or expected to see:
N/A
