### ISSUE TITLE
Is there a built in way to apply a diff patch?

### ISSUE THREAD

**Issue by dudicoco** [koalaman/shellcheck#2222]
Hi,

I've read that order to auto-fix files with shellcheck, we can use the following options:
```
shellcheck file.sh -f diff | git apply
shellcheck file.sh -f diff | patch -p 1
```

When running shellcheck in the context of a pre-commit hook, it doesn't seem like it's possible to pipe the output in order to apply it.
The following doesn't work:
```
  - id: shellcheck
    language: docker_image
    entry: koalaman/shellcheck:v0.7.1 -f diff | patch -p 1
    types:
    - shell
```

I have also tried the https://github.com/shellcheck-py/shellcheck-py hook, but same problem.

Is there a way to apply the diff patch without resorting to pipe?

Thanks

**Comment by koalaman** [comment]
There is no built in functionality for applying patches, no. I don't know pre-commit, but I imagine you can either have the alpine image do it:

    koalaman/shellcheck-alpine:v0.7.1 sh -c 'apk add patch && shellcheck -f diff "$@" | patch -p 1' _

or write a script that invokes `docker run ... | patch -p 1` and invoke it via a `system` hook

**Comment by dudicoco** [comment]
Thanks @koalaman.

I've ended up with the following solution:
```
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.7.2.1
  hooks:
  - id: shellcheck
    name: Check sh files
    entry: bash -c 'shellcheck $@ -f diff | patch -p 1' --
```
