### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by rgarrigue** [koalaman/shellcheck#2299]
#### For new checks and feature suggestions
- [x] https://www.shellcheck.net/ (i.e. the latest commit) currently gives no useful warnings about this
- [x] I searched through https://github.com/koalaman/shellcheck/issues and didn't find anything related

#### Question / Feature request

I saw no mention of this, so to be sure is there a way to configure shellcheck through a file like `.shellcheck` ?

If there's none, this is a feature request :-) And I'ld like to suggest ansible-lint as a great example. The config file is a `.ansible-lint` yaml formatted file like this one

```yaml
skip_list:
  - role-name  # Role name {0} does not match ``^[a-z][a-z0-9_]+$`` pattern

warn_list:
  - empty-string-compare  # Don't compare to empty string
  - no-changed-when  # Commands should not change things if nothing needs doing
  - no-handler  # Tasks that run when changed should likely be handlers

exclude_paths:
  - '../../.ansible'
```

And running ansible-lint tells you how to write .ansible-lint to ignore the issues if you feel like it

![image](https://user-images.githubusercontent.com/1872031/129338714-55605a5d-bf5a-4484-8493-5ce3c935cc4f.png)
