### ISSUE TITLE
"shellcheck-precommit" pre-commit hook fails with the "Executable `docker` not found"

### ISSUE THREAD

**Issue by AIGeneratedUsername** [koalaman/shellcheck#2495]
# Versions and config
```yaml
# .pre-commit-config.yaml


repos:
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.8.0
    hooks:
      - id: shellcheck
```
# Steps to reproduce 
Run hooks in any way, e.g. `pre-commit run --all-files`

# Error

```
ShellCheck v0.8.0........................................................Failed
- hook id: shellcheck
- exit code: 1

Executable `docker` not found
```

The error is so unclear and useless so I even have no idea what is wrong.
