### ISSUE TITLE
Export format to SonarQube

### ISSUE THREAD

**Issue by usinelogicielle** [koalaman/shellcheck#3125]
Hi,

We use shellcheck for Shell quality analysis. 
We currently use the https://github.com/sbaudoin/sonar-shellcheck plugin to upload analyses to SonarQube.
We are faced with 2 problems. The plugin is no longer maintained, and to work it needs to have sonarscanner and shellcheck on the same workstation, which poses a problem since we're doing containerization.
Would it be possible to have a “sonarqube” output format based on their generic import?
https://docs.sonarsource.com/sonarqube-server/latest/analyzing-source-code/importing-external-issues/generic-issue-import-format/

**Comment by usinelogicielle** [comment]
Hello @koalaman, 

Is there any chance to get an answer for this topic? It will be a great option to have a generic report format compatible with  SonarQube. SARIF format is widly used for exemple :)
Thank you for your answer and for your work.

**Comment by ggjulio** [comment]
+1 for github security too!

```
    - name: Upload Trivy scan results to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-results.sarif'
```

Gitlab may support it soon: https://gitlab.com/gitlab-org/gitlab/-/issues/452042
