### ISSUE TITLE
How to install ShellCheck on Travis CI

### ISSUE THREAD

**Issue by hugovk** [koalaman/shellcheck#589]
This isn't a bug, but I just wanted to post this here in case anyone else is looking.

It took me a while to find a way to install on Travis CI, but thanks to [this](https://github.com/whiteinge/ok.sh/blob/master/.travis.yml) got it working like this:

```yaml
language: bash

# Use container-based infrastructure for quicker build start-up
sudo: false

addons:
  apt:
    sources:
    - debian-sid    # Grab shellcheck from the Debian repo (o_O)
    packages:
    - shellcheck

script:
 - shellcheck *.sh

matrix:
  fast_finish: true
```

Thanks!
